version: '3.8'

services:
  crawler-prod:
    build: .
    container_name: hides_blog_crawler_prod
    volumes:
      - ./crawls:/crawls
      - ./config:/config
      - ./tmp:/tmp
    environment:
      - CRAWL_MEMORY_LIMIT=3000
      - WORKERS=2
      - PAGE_TIMEOUT=90
    command: >
      --config /config/production-crawl.yaml
      --collection hides_blog_full
    networks:
      - crawler_network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
    shm_size: 1g

networks:
  crawler_network:
    driver: bridge