# 改善版テストクロール設定
# ページネーションと画像取得を改善

seeds:
  - url: https://hidemiyoshi.jp/blog/
    depth: 5

scopeType: prefix

# クロール設定
workers: 1
pageLoadTimeout: 60000
pageExtraDelay: 3000

# ビヘイビア
behaviors:
  - autoscroll

# ブラウザ設定
userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"
lang: ja-JP

# 画像とリソース取得
extraHops: 1

# 出力設定
generateWACZ: true
text: true
screenshot: fullPage

# テスト用制限
limit: 20
maxPageLimit: 20