# browsertrix-crawler 詳細設定
# https://hidemiyoshi.jp/blog/ アーカイブ用
# 作成日: 2025-08-20
# 総記事数: 約440記事、45ページ

# ========================================
# Seeds設定（開始点）
# ========================================
seeds:
  # メインエントリーポイント
  - url: https://hidemiyoshi.jp/blog/
    depth: 50  # 45ページ + 余裕
    scopeType: prefix

# ========================================
# Scope設定（クロール範囲）
# ========================================
scopeType: prefix
scopeIncludePrefix:
  - https://hidemiyoshi.jp/blog/

# 外部ドメインの許可リスト（必要なCDN）
extraHops: 1
blockRules:
  - url: googletagmanager.com
    type: block
  - url: google-analytics.com
    type: block

# 除外パターン（調査で確認済み）
exclude:
  # WordPress管理系
  - .*\/wp-admin\/.*
  - .*\/wp-login\.php
  - .*\/wp-cron\.php
  
  # フィード・API系
  - .*\/feed\/.*
  - .*\/xmlrpc\.php
  - .*\/wp-json\/.*
  
  # コメント・トラックバック系
  - .*#comment.*
  - .*#respond.*
  - .*\/trackback\/.*
  - .*\?replytocom=.*
  
  # 検索・クエリパラメータ
  - .*\?s=.*
  - .*\?p=.*
  - .*&preview=.*
  
  # その他不要なパス
  - .*\.php$  # 直接のPHPファイル（記事以外）

# ========================================
# クロール動作設定
# ========================================
# ページ読み込み設定
pageLoadTimeout: 90000  # 90秒
pageExtraDelay: 2000    # 追加待機2秒

# ネットワーク待機設定
waitUntil: networkidle2  # ネットワークが安定するまで待機
networkIdleWait: 2000    # 2秒間通信なしで安定と判断

# スクロール設定
behaviors:
  - autoscroll
  - autoplay
behaviorTimeout: 60000  # 60秒
scrollDelay: 1000       # 1秒ごとにスクロール

# 同時実行設定
workers: 2              # 並列ワーカー数
crawlTimeout: 0         # 全体のタイムアウトなし

# リトライ設定
retryFailed: true
retryFailedCount: 2

# ========================================
# ブラウザ設定
# ========================================
# User-Agent（Chrome最新版相当）
userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

# 言語設定
lang: ja-JP
acceptLang: ja-JP,ja;q=0.9,en;q=0.8

# ビューポート設定
screencastPort: 9037
viewport:
  width: 1920
  height: 1080
  deviceScaleFactor: 1
  mobile: false

# ブラウザオプション
browserArgs:
  - --disable-dev-shm-usage
  - --disable-gpu
  - --no-sandbox
  - --disable-setuid-sandbox
  - --disable-web-security
  - --font-render-hinting=none

# ========================================
# 出力設定
# ========================================
# WACZ生成
generateWACZ: true
combineWARC: true

# テキスト抽出
text: true
textExtractMode: always

# スクリーンショット
screenshot: fullPage
screenshotDelay: 2000

# メタデータ
metadata:
  operator: "hides blog archiver"
  description: "Archive of https://hidemiyoshi.jp/blog/"

# ========================================
# 制限設定
# ========================================
# クロール制限（0=無制限）
limit: 0
maxPageLimit: 0

# サイズ制限
sizeLimit: 0  # 無制限
diskUtilization: 90  # ディスク使用率90%で停止

# ========================================
# ログ設定
# ========================================
logging: stats
statsFilename: crawl-stats.json
errorsFilename: crawl-errors.json